# Generated by Django 3.0.4 on 2020-05-18 22:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_CPF', models.CharField(default=0, max_length=16)),
                ('_nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('_email', models.EmailField(blank=True, max_length=200, unique=True, verbose_name='E-Mail')),
                ('_tel', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('_CTPS', models.CharField(max_length=25)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'administrador',
                'verbose_name_plural': 'administradores',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_CPF', models.CharField(default=0, max_length=16)),
                ('_nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('_email', models.EmailField(blank=True, max_length=200, unique=True, verbose_name='E-Mail')),
                ('_tel', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_CPF', models.CharField(default=0, max_length=16)),
                ('_nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('_email', models.EmailField(blank=True, max_length=200, unique=True, verbose_name='E-Mail')),
                ('_tel', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone')),
                ('_CTPS', models.CharField(blank=True, max_length=25, null=True)),
                ('administrador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.Administrador', verbose_name='Administradores')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'monitor',
                'verbose_name_plural': 'monitores',
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_nome_pet', models.CharField(max_length=30, verbose_name='Nome do pet')),
                ('_tipo', models.CharField(default='Cachorro', max_length=50, verbose_name='Tipo')),
                ('_porte', models.PositiveIntegerField(choices=[(1, 'Pequeno'), (2, 'Médio'), (3, 'Grande')], default=1, verbose_name='porte do mascote')),
                ('_especie', models.CharField(max_length=50, null=True, verbose_name='Espécie:')),
                ('_racao', models.CharField(max_length=30, verbose_name='Ração')),
                ('data_entrada', models.DateField(auto_now_add=True, verbose_name='Data de entrada')),
                ('dono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente', verbose_name='Dono')),
            ],
            options={
                'verbose_name': 'mascote',
                'verbose_name_plural': 'mascotes',
            },
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_nome', models.CharField(default='Nome do serviço prestado', max_length=300, verbose_name='Nome do serviço')),
                ('_detalhes', models.TextField(default='Serviço prestado', max_length=1000, verbose_name='Detalhes')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Monitor', verbose_name='Monitor que aplicou')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Pet', verbose_name='Pet que recebeu')),
            ],
            options={
                'verbose_name': 'serviço',
                'verbose_name_plural': 'serviços',
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='monitor_escolhido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.Monitor', verbose_name='Monitor responsável'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
