# Generated by Django 3.0.4 on 2020-04-30 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='data_entrada',
            field=models.DateField(blank=True, verbose_name='Data de entrada'),
        ),
    ]
