# Generated by Django 3.0.4 on 2020-05-05 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='_dono',
            new_name='dono',
        ),
    ]
