# Generated by Django 3.0.4 on 2020-05-18 22:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicos',
            name='data_criacao',
        ),
        migrations.AddField(
            model_name='servicos',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Data de ocorrência'),
            preserve_default=False,
        ),
    ]
