# Generated by Django 3.0.4 on 2020-04-20 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20200420_1055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='administrador',
            options={'verbose_name': 'administrador', 'verbose_name_plural': 'administradores'},
        ),
        migrations.RenameField(
            model_name='administrador',
            old_name='CPF',
            new_name='_CPF',
        ),
        migrations.RenameField(
            model_name='administrador',
            old_name='CTPS',
            new_name='_CTPS',
        ),
        migrations.RenameField(
            model_name='administrador',
            old_name='nome',
            new_name='_nome',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='CPF',
            new_name='_CPF',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='nome',
            new_name='_nome',
        ),
    ]
