# Generated by Django 3.0.4 on 2020-04-20 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_auto_20200420_1059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'verbose_name': 'cliente', 'verbose_name_plural': 'clientes'},
        ),
        migrations.AlterModelOptions(
            name='monitor',
            options={'verbose_name': 'monitor', 'verbose_name_plural': 'monitores'},
        ),
        migrations.AlterModelOptions(
            name='pet',
            options={'verbose_name': 'mascote', 'verbose_name_plural': 'mascotes'},
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='email',
            new_name='_email',
        ),
        migrations.RenameField(
            model_name='cliente',
            old_name='tel',
            new_name='_tel',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='nome',
            new_name='_nome_pet',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='Porte',
            new_name='_porte',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='raca',
            new_name='_raca',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='racao',
            new_name='_racao',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='servicos',
            new_name='_servicos',
        ),
        migrations.AlterField(
            model_name='pet',
            name='dono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente'),
        ),
    ]
