# Generated by Django 3.0.4 on 2020-04-20 14:35

import cliente.models
from django.db import migrations, models
import django.db.models.deletion
import django_enum_choices.choice_builders
import django_enum_choices.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_auto_20200420_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='_nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='_email',
            field=models.EmailField(blank=True, max_length=200, verbose_name='E-Mail'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='_nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='_tel',
            field=models.CharField(max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='_nome_pet',
            field=models.CharField(max_length=30, verbose_name='Nome do pet'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='_porte',
            field=django_enum_choices.fields.EnumChoiceField(choice_builder=django_enum_choices.choice_builders.value_value, choices=[('P', 'P'), ('M', 'M'), ('G', 'G')], enum_class=cliente.models.Porte, max_length=1, verbose_name='Porte'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='_raca',
            field=models.CharField(max_length=50, verbose_name='Raça'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='_racao',
            field=models.CharField(max_length=30, verbose_name='Ração'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='_servicos',
            field=models.TextField(blank=True, max_length=400, verbose_name='Serviços'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='dono',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente', verbose_name='Dono'),
        ),
    ]
