# Generated by Django 3.0.4 on 2020-05-04 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_administrador_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='clientes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.Cliente', verbose_name='clientes'),
        ),
    ]
