# Generated by Django 3.0.4 on 2020-05-04 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_monitor_clientes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='clientes',
        ),
        migrations.AddField(
            model_name='cliente',
            name='monitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.Monitor', verbose_name='Monitor responsável'),
        ),
    ]
