# Generated by Django 3.0.4 on 2020-04-20 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0005_auto_20200420_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='_email',
            field=models.EmailField(blank=True, max_length=200, verbose_name='E-Mail'),
        ),
        migrations.AddField(
            model_name='administrador',
            name='_tel',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='_tel',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
    ]
