# Generated by Django 3.0.4 on 2020-04-20 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_auto_20200420_1147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='dono',
            new_name='_dono',
        ),
    ]
