# Generated by Django 3.0.4 on 2020-05-04 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0006_auto_20200504_1110'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='monitor',
            new_name='monitor_escolhido',
        ),
    ]
