# Generated by Django 3.0.4 on 2020-04-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0007_auto_20200420_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='_tipo',
            field=models.CharField(default='Cachorro', max_length=50, verbose_name='Tipo'),
        ),
    ]
