# Generated by Django 3.0.4 on 2020-04-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0008_pet__tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='_raca',
        ),
        migrations.AddField(
            model_name='pet',
            name='_especie',
            field=models.CharField(max_length=50, null=True, verbose_name='Espécie:'),
        ),
    ]
